### ISSUE TITLE
[BUG] Getting internal error on fresh install of ts-prune

### ISSUE THREAD

**Issue by benwinding** [nadeesha/ts-prune#103]
**Describe the bug**
Error on fresh project 

```
› ts-prune       
/home/ben/.nvm/versions/node/v10.20.0/lib/node_modules/ts-prune/lib/analyzer.js:161
    var referencedInFile = Object.entries(referenceCounts).flatMap(function (_a) {
                                                           ^

TypeError: Object.entries(...).flatMap is not a function
    at Object.exports.getPotentiallyUnused (/home/ben/.nvm/versions/node/v10.20.0/lib/node_modules/ts-prune/lib/analyzer.js:161:60)
    at /home/ben/.nvm/versions/node/v10.20.0/lib/node_modules/ts-prune/lib/analyzer.js:191:21
    at Array.forEach (<anonymous>)
```
**Additional context**

```
version: 0.8.4
   node: 10.20.0
     OS: Ubuntu 64bit
```
**tsconfig.json**
```
{
  "compilerOptions": {
    "outDir": "dist",
    "module": "es2015",
    "moduleResolution": "node",
    "target": "es5",
    "lib": ["es6", "es2016", "dom"],
    "baseUrl": "src",
    "strict": true,
    "preserveConstEnums": true,
    "sourceMap": true,
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "typeRoots": ["node_modules/@types", "src/types.d.ts"]
  },
  "include": ["src"],
  "exclude": ["node_modules", "dist"]
}
```

**Comment by staff0rd** [comment]
Got the same, solved by bumping node version to one that supports `flatmap`. node v12+ works.

**Comment by adaspt** [comment]
If you are still using node v10, workaround is to create `ts-prune.config.js` at the project root:
```
require('core-js/stable');
module.exports = {};
```

**Comment by nadeesha** [comment]
Ah, this is annoying. Let me try and find a fix for this in the project itself.

**Comment by SimonJang** [comment]
I've opened a PR since I was facing the same issue.
