### ISSUE TITLE
Errors running ts-prune v0.2+

### ISSUE THREAD

**Issue by pelotom** [nadeesha/ts-prune#33]
ts-prune v0.1.3 and before work fine for me, but starting in v0.2.0 I get the following error:

```
$ ts-prune
node_modules/ts-prune/lib/analyzer.js:35
            .getText()
            ^

TypeError: Cannot read property 'getText' of undefined
    at node_modules/ts-prune/lib/analyzer.js:35:13
    at Array.forEach (<anonymous>)
    at emitDefinitelyUsed (node_modules/ts-prune/lib/analyzer.js:32:34)
    at node_modules/ts-prune/lib/analyzer.js:69:9
    at Array.forEach (<anonymous>)
    at Object.exports.analyze (node_modules/ts-prune/lib/analyzer.js:67:30)
    at Object.exports.run (node_modules/ts-prune/lib/runner.js:18:16)
    at Object.<anonymous> (node_modules/ts-prune/lib/index.js:5:10)
    at Module._compile (internal/modules/cjs/loader.js:723:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
error Command failed with exit code 1.
```

And in v0.2.1 there is a slightly different error:

```
$ ts-prune
node_modules/ts-prune/lib/analyzer.js:36
                file: decl.getModuleSpecifierSourceFile().getFilePath(),
                                                         ^

TypeError: Cannot read property 'getFilePath' of undefined
    at node_modules/ts-prune/lib/analyzer.js:36:58
    at Array.forEach (<anonymous>)
    at emitDefinitelyUsed (node_modules/ts-prune/lib/analyzer.js:33:34)
    at node_modules/ts-prune/lib/analyzer.js:66:9
    at Array.forEach (<anonymous>)
    at Object.exports.analyze (node_modules/ts-prune/lib/analyzer.js:64:30)
    at Object.exports.run (node_modules/ts-prune/lib/runner.js:18:16)
    at Object.<anonymous> (node_modules/ts-prune/lib/index.js:5:10)
    at Module._compile (internal/modules/cjs/loader.js:723:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
error Command failed with exit code 1.
```

**Comment by OliverJAsh** [comment]
1st error was reported and fixed here: https://github.com/nadeesha/ts-prune/issues/28.

I also have the 2nd error.

**Comment by nadeesha** [comment]
Thanks for reporting this. I've pushed `v0.2.2` which should hopefully fix this with #34.

I'm unable to reproduce this with my test cases. Can you please let me know what type of an import declaration breaks this code?

**Comment by OliverJAsh** [comment]
> I'm unable to reproduce this with my test cases.

Can you provide any steps to help find the culprit in a large project?

**Comment by OliverJAsh** [comment]
Can confirm I get no error with 0.2.2 🎉

**Comment by pelotom** [comment]
Fixed for me too, thanks!

**Comment by shejal-Hauper-fe** [comment]
@pelotom I have installed ts-prune but when I'm trying to do anything this is saying ts-prune : command not found. 
![image](https://user-images.githubusercontent.com/103435307/191902603-a3fd9071-2f30-4cff-983e-549d0128b481.png)
![image](https://user-images.githubusercontent.com/103435307/191902843-c193f58f-224e-49db-bcff-539a1c4f2cb3.png)
Can you please tell me what is the reason behind this or do I have missed out something?
