### ISSUE TITLE
[BUG] TypeError: Object.entries(...).flatMap is not a function

### ISSUE THREAD

**Issue by rdvanbuuren** [nadeesha/ts-prune#93]
**Describe the bug**
Runnig the application throws a TypeError: Object.entries(...).flatMap is not a function.

`λ ts-prune
C:\Users\Rick van Buuren\AppData\Roaming\npm\node_modules\ts-prune\lib\analyzer.js:161
    var referencedInFile = Object.entries(referenceCounts).flatMap(function (_a) {
                                                           ^
TypeError: Object.entries(...).flatMap is not a function
    at Object.exports.getPotentiallyUnused (C:\Users\Rick van Buuren\AppData\Roaming\npm\node_modules\ts-prune\lib\analyzer.js:161:60)
    at C:\Users\Rick van Buuren\AppData\Roaming\npm\node_modules\ts-prune\lib\analyzer.js:191:21
    at Array.forEach (<anonymous>)
    at Object.exports.analyze (C:\Users\Rick van Buuren\AppData\Roaming\npm\node_modules\ts-prune\lib\analyzer.js:189:30)
    at Object.exports.run (C:\Users\Rick van Buuren\AppData\Roaming\npm\node_modules\ts-prune\lib\runner.js:22:16)
    at Object.<anonymous> (C:\Users\Rick van Buuren\AppData\Roaming\npm\node_modules\ts-prune\lib\index.js:6:10)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)`

**To Reproduce**
1. Install application `npm install ts-prune -g`.
2. Check if latest (ts-prune@0.8.4) is installed.
3. Run `ts-prune` in source folder

**Expected behavior**
The application outputs anything else than a TypeError.

**Comment by KaeruCT** [comment]
[According to MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array), `Array.prototype.flatMap` was added in Node.js 11.0.0

So just make sure you are running version `11.0.0` or higher

**Comment by nadeesha** [comment]
Yes, running it in a compatible node-version (preferably the LTS) would work. I think including the `flatMap` shim as a interim solution would be good as well.

**Comment by rdvanbuuren** [comment]
Thank you! Upgrading to Node.js 12 resolved the issue 👍
